# Generated by Django 4.0.1 on 2022-01-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_proxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compassuser',
            name='member_number',
            field=models.IntegerField(default=-1, editable=False, unique=True),
        ),
    ]
