# Generated by Django 4.0.1 on 2022-01-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_proxy', '0002_alter_compassuser_member_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='compassuser',
            name='can_create_oauth_tokens',
            field=models.BooleanField(default=False),
        ),
    ]
