# Generated by Django 4.0.1 on 2022-01-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_proxy', '0003_compassuser_can_create_oauth_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compassuser',
            name='member_number',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
